include $(GOROOT)/src/Make.inc

TARG=go-pdf/pdf

GOFILES=\
  objects.go\
  doc_writer.go\
  page_writer.go\
  page_style.go\
  support.go\
  units.go\
  graph_writer.go\
  misc_writer.go\

include $(GOROOT)/src/Make.pkg
