include $(GOROOT)/src/Make.inc

TARG=go-pdf/codepage

GOFILES=\
  codepage.go\
  cp1250.go\
  cp1251.go\
  cp1252.go\
  cp1253.go\
  cp1254.go\
  cp1256.go\
  cp1257.go\
  cp1258.go\
  cp874.go\

include $(GOROOT)/src/Make.pkg
