include $(GOROOT)/src/Make.inc

TARG=go-pdf/codepage

GOFILES=\
  codepage.go\
  ascii.go\
  iso-8859-1.go\
  iso-8859-2.go\
  iso-8859-3.go\
  iso-8859-4.go\
  iso-8859-5.go\
  iso-8859-6.go\
  iso-8859-7.go\
  iso-8859-8.go\
  iso-8859-9.go\
  iso-8859-10.go\
  iso-8859-11.go\
  iso-8859-13.go\
  iso-8859-14.go\
  iso-8859-15.go\
  iso-8859-16.go\
  cp1250.go\
  cp1251.go\
  cp1252.go\
  cp1253.go\
  cp1254.go\
  cp1256.go\
  cp1257.go\
  cp1258.go\
  cp874.go\
  cpselect.go\

include $(GOROOT)/src/Make.pkg
