package ltml

import (
	"bytes"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rowland/leadtype/afm_fonts"
	"github.com/rowland/leadtype/ltml/ltpdf"
	"github.com/rowland/leadtype/pdf"
)

func renderLTMLPDF(t *testing.T, input string, assetFS fs.FS) string {
	t.Helper()

	var opts []ParseOption
	if assetFS != nil {
		opts = append(opts, WithAssetFS(assetFS))
	}
	doc, err := Parse([]byte(input), opts...)
	if err != nil {
		t.Fatal(err)
	}

	baseWriter := pdf.NewDocWriter()
	fonts, err := afm_fonts.Default()
	if err != nil {
		t.Fatal(err)
	}
	baseWriter.AddFontSource(fonts)
	if assetFS != nil {
		baseWriter.SetAssetFS(assetFS)
	}
	writer := &ltpdf.DocWriter{DocWriter: baseWriter}

	if err := doc.Print(writer); err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	if _, err := baseWriter.WriteTo(&buf); err != nil {
		t.Fatal(err)
	}
	return buf.String()
}

func TestAccessibilityReplacementTextIsReservedForArabic(t *testing.T) {
	tests := []struct {
		name string
		text string
		want string
	}{
		{name: "latin", text: "Hello world"},
		{name: "chinese", text: "中文可逐字选择"},
		{name: "arabic", text: "مرحبا بالعالم", want: "مرحبا بالعالم"},
		{name: "mixed arabic", text: "Page مرحبا 1", want: "Page مرحبا 1"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := accessibilityReplacementText(tt.text); got != tt.want {
				t.Fatalf("accessibilityReplacementText(%q) = %q, want %q", tt.text, got, tt.want)
			}
		})
	}
	if got := accessibilityTextLanguage("مرحبا"); got != "ar" {
		t.Fatalf("Arabic accessibility language = %q, want ar", got)
	}
	if got := accessibilityTextLanguage("中文"); got != "" {
		t.Fatalf("Chinese accessibility language = %q, want empty", got)
	}
}

func TestLTML_DocumentLanguageIsWrittenToCatalog(t *testing.T) {
	pdfText := renderLTMLPDF(t, `<ltml ua="true" lang="ar"><page><p>hello</p></page></ltml>`, nil)
	if !strings.Contains(pdfText, "/Lang (ar)") {
		t.Fatalf("PDF catalog missing document language:\n%s", pdfText)
	}
}

func TestArabicProgramArtifactAccessibilityAndExtraction(t *testing.T) {
	pdfPath := filepath.Join("samples", "test_033_arabic_program.pdf")
	pdfData, err := os.ReadFile(pdfPath)
	if err != nil {
		t.Fatal(err)
	}
	pdfText := string(pdfData)
	for _, want := range []string{"/Lang (ar)", "/S /Table", "/S /TR", "/S /TH", "/S /TD"} {
		if !strings.Contains(pdfText, want) {
			t.Fatalf("Arabic artifact missing %q", want)
		}
	}
	if _, err := exec.LookPath("pdftotext"); err != nil {
		t.Skip("pdftotext is unavailable")
	}
	raw, err := exec.Command("pdftotext", pdfPath, "-").CombinedOutput()
	if err != nil {
		t.Fatalf("pdftotext: %v\n%s", err, raw)
	}
	logical := decodePopplerRTLText(string(raw))
	for _, want := range []string{
		"برنامج أمسيات الحي الثقافية",
		"مساء الثلاثاء الرابع عشر من أبريل",
		"community@citylibrary.example",
	} {
		if !strings.Contains(logical, want) {
			t.Fatalf("decoded extraction missing %q; raw=%q logical=%q", want, string(raw), logical)
		}
	}
}

// decodePopplerRTLText converts Poppler's plain-text transport convention
// (visual codepoint order inside an RLE/PDF pair) back to logical order. The
// controls are generated by Poppler and are not present in PDF ActualText.
func decodePopplerRTLText(text string) string {
	runes := []rune(text)
	out := make([]rune, 0, len(runes))
	for i := 0; i < len(runes); i++ {
		if runes[i] != '\u202B' {
			if runes[i] != '\u202C' && runes[i] != '\u202A' {
				out = append(out, runes[i])
			}
			continue
		}
		end := i + 1
		for end < len(runes) && runes[end] != '\u202C' {
			end++
		}
		for j := end - 1; j > i; j-- {
			if runes[j] != '\u202A' && runes[j] != '\u202C' {
				out = append(out, runes[j])
			}
		}
		i = end
	}
	return string(out)
}

func TestLTML_UAEnablesTaggedPDF(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <p>Hello <a uri="https://example.com">world</a></p>
  </page>
</ltml>`, nil)

	for _, fragment := range []string{
		"%PDF-1.7\n",
		"/StructTreeRoot",
		"/S /P",
		"/S /Link",
	} {
		if !strings.Contains(pdfText, fragment) {
			t.Fatalf("expected tagged fragment %q in output:\n%s", fragment, pdfText)
		}
	}
	if strings.Contains(pdfText, "/ActualText (Hello world)") {
		t.Fatalf("text structure should rely on rendered text and ToUnicode:\n%s", pdfText)
	}
}

func TestLTML_WithoutUAAccessibilityAttrsAreIgnored(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml>
  <page>
    <label role="H1" alt="ignored">Hello</label>
    <image src="pdf/testdata/eidetic.png" alt="ignored image" width="32" height="32" />
  </page>
</ltml>`, os.DirFS(".."))

	if !strings.Contains(pdfText, "%PDF-1.7\n") {
		t.Fatalf("expected untagged PDF header:\n%s", pdfText)
	}
	for _, fragment := range []string{"/StructTreeRoot", "/S /H1", "/S /Figure", "/ActualText ("} {
		if strings.Contains(pdfText, fragment) {
			t.Fatalf("did not expect %q in untagged output:\n%s", fragment, pdfText)
		}
	}
}

func TestLTML_WriterTaggedPDFDefaultIsPreserved(t *testing.T) {
	doc, err := Parse([]byte(`
<ltml>
  <page>
    <p>Hello world</p>
  </page>
</ltml>`))
	if err != nil {
		t.Fatal(err)
	}

	baseWriter := pdf.NewDocWriter()
	fonts, err := afm_fonts.Default()
	if err != nil {
		t.Fatal(err)
	}
	baseWriter.AddFontSource(fonts)
	baseWriter.EnableTaggedPDF(true)
	writer := &ltpdf.DocWriter{DocWriter: baseWriter}

	if err := doc.Print(writer); err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	if _, err := baseWriter.WriteTo(&buf); err != nil {
		t.Fatal(err)
	}
	pdfText := buf.String()
	for _, fragment := range []string{"/StructTreeRoot", "/S /P"} {
		if !strings.Contains(pdfText, fragment) {
			t.Fatalf("expected tagged fragment %q in output:\n%s", fragment, pdfText)
		}
	}
	if strings.Contains(pdfText, "/ActualText (Hello world)") {
		t.Fatalf("text structure should not contain replacement text:\n%s", pdfText)
	}
}

func TestLTML_LegacyPDFAttrsDoNotAffectOutput(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <label pdf.tag="H1" pdf.actual-text="Wrong">Hello</label>
  </page>
</ltml>`, nil)

	if !strings.Contains(pdfText, "/S /P") {
		t.Fatalf("expected default label role in output:\n%s", pdfText)
	}
	if strings.Contains(pdfText, "/S /H1") {
		t.Fatalf("did not expect legacy pdf.tag override in output:\n%s", pdfText)
	}
	if strings.Contains(pdfText, "/ActualText") {
		t.Fatalf("legacy or automatic replacement text reached output:\n%s", pdfText)
	}
}

func TestLTML_LabelRoleOverride(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <label role="H1">Heading</label>
  </page>
</ltml>`, nil)

	if !strings.Contains(pdfText, "/S /H1") {
		t.Fatalf("expected H1 role override in output:\n%s", pdfText)
	}
	if strings.Contains(pdfText, "/ActualText (Heading)") {
		t.Fatalf("text heading should rely on rendered text and ToUnicode:\n%s", pdfText)
	}
}

func TestLTML_RoleArtifactSuppressesLabelAccessibility(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <label role="ArTiFaCt">42</label>
  </page>
</ltml>`, nil)

	if strings.Contains(pdfText, "/S /P") || strings.Contains(pdfText, "/ActualText (42)") {
		t.Fatalf("did not expect label tagging for artifact role:\n%s", pdfText)
	}
	if !strings.Contains(pdfText, "/Artifact BMC") {
		t.Fatalf("expected artifact marked content for artifact role:\n%s", pdfText)
	}
}

func TestLTML_InvalidRoleFallsBackToDefaultRole(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <label role="bad role!">Hello</label>
  </page>
</ltml>`, nil)

	if !strings.Contains(pdfText, "/S /P") {
		t.Fatalf("expected fallback to default label role in output:\n%s", pdfText)
	}
	if strings.Contains(pdfText, "/S /bad") {
		t.Fatalf("did not expect invalid role to flow through to output:\n%s", pdfText)
	}
}

func TestLTML_DynamicPageNoRemainsRenderedText(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <label>Page <pageno/></label>
  </page>
</ltml>`, nil)

	if strings.Contains(pdfText, "/ActualText (Page 1)") {
		t.Fatalf("dynamic text should not become replacement text:\n%s", pdfText)
	}
	if !strings.Contains(pdfText, "(Page 1) Tj") && !strings.Contains(pdfText, "<") {
		t.Fatalf("expected page number content to render as text:\n%s", pdfText)
	}
}

func TestLTML_PreRoleUsesRenderedText(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <pre role="Code">
      if x &lt; 1 {
        return
      }
    </pre>
  </page>
</ltml>`, nil)

	if !strings.Contains(pdfText, "/S /Code") {
		t.Fatalf("expected pre role in output:\n%s", pdfText)
	}
	if strings.Contains(pdfText, "/ActualText") {
		t.Fatalf("preformatted text should not become replacement text:\n%s", pdfText)
	}
}

func TestLTML_WrappedLinkReusesOneLinkElement(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <p width="1in"><a uri="https://example.com">One two three four five six</a></p>
  </page>
</ltml>`, nil)

	if count := strings.Count(pdfText, "/S /Link"); count != 1 {
		t.Fatalf("link struct element count = %d, want 1\n%s", count, pdfText)
	}
	if count := strings.Count(pdfText, "/Type /MCR"); count < 2 {
		t.Fatalf("marked-content ref count = %d, want at least 2\n%s", count, pdfText)
	}
}

func TestLTML_ImageRequiresAlt(t *testing.T) {
	withAlt := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <image src="pdf/testdata/eidetic.png" alt="logo" width="32" height="32" />
  </page>
</ltml>`, os.DirFS(".."))
	if !strings.Contains(withAlt, "/S /Figure") || !strings.Contains(withAlt, "/ActualText (logo)") {
		t.Fatalf("expected figure with actual text for image alt:\n%s", withAlt)
	}

	withoutAlt := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <image src="pdf/testdata/eidetic.png" width="32" height="32" />
  </page>
</ltml>`, os.DirFS(".."))
	if strings.Contains(withoutAlt, "/S /Figure") {
		t.Fatalf("did not expect figure tag without image alt:\n%s", withoutAlt)
	}
	if !strings.Contains(withoutAlt, "/Artifact BMC") {
		t.Fatalf("expected decorative image to render as artifact:\n%s", withoutAlt)
	}
}

func TestLTML_GraphicRoleOverrideRequiresAlt(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <image src="pdf/testdata/eidetic.png" alt="diagram" role="Formula" width="32" height="32" />
  </page>
</ltml>`, os.DirFS(".."))

	if !strings.Contains(pdfText, "/S /Formula") || !strings.Contains(pdfText, "/ActualText (diagram)") {
		t.Fatalf("expected explicit graphic role override with alt:\n%s", pdfText)
	}
}

func TestLTML_GraphicArtifactRoleSuppressesAltTagging(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <image src="pdf/testdata/eidetic.png" alt="diagram" role="artifact" width="32" height="32" />
  </page>
</ltml>`, os.DirFS(".."))

	if strings.Contains(pdfText, "/S /Figure") || strings.Contains(pdfText, "/ActualText (diagram)") {
		t.Fatalf("did not expect figure tagging for artifact role:\n%s", pdfText)
	}
	if !strings.Contains(pdfText, "/Artifact BMC") {
		t.Fatalf("expected graphic artifact marked content for artifact role:\n%s", pdfText)
	}
}

func TestLTML_SVGRequiresAlt(t *testing.T) {
	withAlt := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <svg src="test_034_scene.svg" alt="logo" width="32" height="32" />
  </page>
</ltml>`, os.DirFS("samples"))
	if !strings.Contains(withAlt, "/S /Figure") || !strings.Contains(withAlt, "/ActualText (logo)") {
		t.Fatalf("expected figure with actual text for svg:\n%s", withAlt)
	}

	withoutAlt := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <svg src="test_034_scene.svg" width="32" height="32" />
  </page>
</ltml>`, os.DirFS("samples"))
	if strings.Contains(withoutAlt, "/S /Figure") {
		t.Fatalf("did not expect figure tag without svg alt:\n%s", withoutAlt)
	}
	if !strings.Contains(withoutAlt, "/Artifact BMC") {
		t.Fatalf("expected decorative svg to render as artifact:\n%s", withoutAlt)
	}
}

func TestLTML_LineAndShapeRequireAlt(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <line angle="0" length="1in" />
    <circle width="1in" height="1in" />
    <line angle="0" length="1in" alt="separator" />
    <circle width="1in" height="1in" alt="badge" />
  </page>
</ltml>`, nil)

	if count := strings.Count(pdfText, "/S /Figure"); count != 2 {
		t.Fatalf("figure count = %d, want 2\n%s", count, pdfText)
	}
	for _, fragment := range []string{"/ActualText (separator)", "/ActualText (badge)", "/Artifact BMC"} {
		if !strings.Contains(pdfText, fragment) {
			t.Fatalf("expected %q in output:\n%s", fragment, pdfText)
		}
	}
}

func TestLTML_ContainerAndParagraphRoles(t *testing.T) {
	pdfText := renderLTMLPDF(t, `
<ltml ua="true">
  <page>
    <div role="L">
      <p role="LI">Item one</p>
    </div>
    <div layout="table" cols="1" role="Table">
      <label role="TD">Cell</label>
    </div>
  </page>
</ltml>`, nil)

	for _, fragment := range []string{"/S /L", "/S /LI", "/S /Table", "/S /TR", "/S /TD"} {
		if !strings.Contains(pdfText, fragment) {
			t.Fatalf("expected role fragment %q in output:\n%s", fragment, pdfText)
		}
	}
}
