include $(GOROOT)/src/Make.inc

TARG=go-pdf/ttf

GOFILES=\
  font.go\
  font_collection.go\
  font_info.go\
  cmap_table.go\
  head_table.go\
  hhea_table.go\
  hmtx_table.go\
  maxp_table.go\
  name_table.go\
  os2_table.go\
  post_table.go\
  vhea_table.go\
  vmtx_table.go\
  mac_roman_post_names.go\
  support.go\
  codepoint_ranges.go\

include $(GOROOT)/src/Make.pkg
